language: csharp
solution: JSIL_NoXNA_NoLibraries.sln

before_install:
  - nvm install 0.10
  - wget -P /tmp/avim -N https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-mozilla-central/jsshell-linux-x86_64.zip
  - unzip -d /tmp/js /tmp/avim/jsshell-linux-x86_64.zip
  - export PATH=$PATH:/tmp/js
  
install:
  - nuget restore JSIL_NoXNA_NoLibraries.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner 
  - cd JSIL.Libraries
  - npm install 
  - cd ..
  
script:
  - xbuild /p:Configuration=Release /v:m JSIL_NoXNA_NoLibraries.sln
  - cd JSIL.Libraries
  - npm test
  - cd ..
  - rm bin/nunit.core.dll
  - rm bin/nunit.core.interfaces.dll
  - rm bin/nunit.util.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Tests.DCE.dll ./bin/SimpleTests.dll ./bin/Tests.dll --run:JSIL.Tests.ThreadingTests  --include:A
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Tests.DCE.dll ./bin/SimpleTests.dll ./bin/Tests.dll --run:JSIL.Tests.ThreadingTests  --include:B
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Tests.DCE.dll ./bin/SimpleTests.dll ./bin/Tests.dll --run:JSIL.Tests.ThreadingTests  --include:C
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./bin/Tests.DCE.dll ./bin/SimpleTests.dll ./bin/Tests.dll --run:JSIL.Tests.ThreadingTests  --include:FailsOnMono

env:
  - JsilUseAppDomainsInTest=true
  